### ISSUE TITLE
Can read but not update files in Word

### ISSUE THREAD

**Issue by V8gremlin** [wa2c/cifs-documents-provider#51] opened 2023-10-25 20:29 UTC
I have connected to a Windows share (Server 2019) using CIFS provider and can open files on it but cannot save any changes made to the files. No error message but no update written.
Also new files saved to the share are 0kb long.

**Comment by RebelliousX** [comment] 2023-10-26 18:47
I can confirm this,  I tried to open a text file using Word, and it said it was `Read-only` at the top title bar.

Log shows:
`openDocument: documentId=192.168.4.32/Public/2.txt
getCallback: uri=smb://192.168.4.32/Public/2.txt, mode=R`

If I open the same file using Mixplorer app's text editor from the File picker directly,
it will allow write operation to the file.

I am not seeing how the Read/Write permission is determined from the code. `openDocument()` always has `AccessMode.R` for SAF. And it relies on CIFS libraries like JCIFS and SMBJ to determine the permissions based on the user's credentials. 
I am not sure it will be easy to fix without major rewrite of the code? Maybe by using Virtual Files instead of proxy callbacks alone. I could be wrong, not sure.

**Comment by V8gremlin** [comment] 2023-10-26 19:45
The problem does seems to be with files that are opened directly in Word.
If I edit the file and then share it (instead of save) to the CIFS provider, it is written OK to the network folder.

**Comment by RebelliousX** [comment] 2023-10-26 19:51
Thanks for clarifying. 

I will see what I can do, but I might leave it to the expert @wa2c, 
since this might be related to other issues related to renaming files too 
(rename doesn't work, delete works in SMBJ for example).

**Comment by V8gremlin** [comment] 2023-10-26 22:00
If you open a txt file in Word it says it is read-only and asks if you want to save a copy in office format to be able to edit (that is an Android Word "feature") So that is not quite the issue I have been having. I opened a .docx file on the server and then saved the file. But the changes were not written back. So you might find a different log message perhaps with that scenario

**Comment by wa2c** [comment] 2023-11-13 13:33
@V8gremlin 
I found the cause of this problem.
It will be fixed in next version.

https://github.com/wa2c/cifs-documents-provider/commit/66b958cd3edf6dbe5e49a974cf9c96dd1731c8e5


@RebelliousX 
Thank you.

**Comment by wa2c** [comment] 2023-11-15 07:13
@V8gremlin 
Ver.2.0.0 released. Please check it.

**Comment by V8gremlin** [comment] 2023-11-16 16:53
Have checked, and files are now saved properly

Thanks

**Closed** 2024-04-15 17:46 UTC
