### ISSUE TITLE
Use of the 127.0.0.0/8 internal network address range?

### ISSUE THREAD

**Issue by NoteAfterNote** [wa2c/cifs-documents-provider#78] opened 2024-04-28 02:01 UTC
**Is your feature request related to a problem? Please describe.**
In version 2.2.1 with no physical network connection established adding a folder/connection by pressing the "+" button exits the app. The app is running on Android 11.

**Describe the solution you'd like**
Use of 127.0.0.0/8 (localhost, loopback).

**Comment by wa2c** [comment] 2024-04-28 06:25
@NoteAfterNote 
Thank you for reporting the issue.
An error when searching for a host could not be handled.
This issue will be fixed in the next version.

**Comment by wa2c** [comment] 2024-05-13 10:19
@NoteAfterNote 
Ver.2.3.0 released. Could you please check if the problem is resolved?

**Comment by NoteAfterNote** [comment] 2024-05-14 03:46
> @NoteAfterNote Ver.2.3.0 released. Could you please check if the problem is resolved?

@wa2c, the problem is solved. Thank you for fixing it.

**Closed** 2024-05-14 15:58 UTC
Labels: enhancement
